# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '--build-arg', 'url=https://github.com/heptio/java-prototype.git', '--build-arg', 'project=java-prototype', '--tag=gcr.io/$PROJECT_ID/java-prototype', '.']

images:
- 'gcr.io/$PROJECT_ID/java-prototype'
